name: entity_sync_generator
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  entity_sync:
    git:
      url: https://github.com/anhphamduy/entity_sync
#    path: ../entity_sync
  analyzer: ">=0.40.0 <=2.1.0"

  source_gen: ^0.9.4
  build: ^1.6.0
#
#dev_dependencies:
#  test: ^1.16.5
