name: entity_sync_generator
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  entity_sync:
    git:
      url: https://github.com/cmberryau/entity_sync
#    path: ../entity_sync
      ref: "master-2"
  analyzer: ^2.1.0

  source_gen: ^1.2.0
  build: ^2.1.1
#
#dev_dependencies:
#  test: ^1.16.5
